name: trigger-remote-workflow
on:
  workflow_dispatch:

jobs:
  remote-job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl \
         -X POST \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token ${{ secrets.TEST_PAT }}" \
         https://api.github.com/repos/hippyod/cicd-infra/actions/workflows/remote-workflow.yml/dispatches \
         -d '{"ref":"master", "inputs": {"repo": "${{ env.GITHUB_REPOSITORY }}", "ref": "${{ env.GITHUB_REF }}"}}'

