name: trigger-remote-workflow
on:
  workflow_dispatch:
    inputs:
      workflow-name:
        description: Name of workflow to run in cicd-infra
        required: true
        default: remote-workflow

jobs:
  remote-job:
    runs-on: ubuntu-latest
    env:
      CICD_INFRA_SVC_ACCT_PAT: ${{ secrets.TEST_PAT }}
      WORKFLOW_NAME: ${{ github.event.inputs.workflow-name }}
    steps:
    - name: Checkout CICD infra library
      uses: actions/checkout@v2
      with:
        repository: hippyod/cicd-infra
        ref: master
        path: cicd-infra
        token: ${{ secrets.TEST_PAT }}
    - name: Trigger remote workflow
      run: |
        ${GITHUB_WORKSPACE}/cicd-infra/scripts/trigger-remote-workflow/trigger-remote-workflow.sh ${WORKFLOW_NAME} ${CICD_INFRA_SVC_ACCT_PAT}

